name: Node CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.15.3'
    - name: npm install, build, and test
      run: |
        cd ./public_html
        npm install
        npm run build --if-present
        npm test
    - name: gatsby build
      run: |
        cd ./public_html
        ./node_modules/.bin/gatsby build
    - uses: actions/upload-artifact@master
      with:
        name: artifacts
        path: ./public_html/public