name: CD
on: 
  push:
    branches:
    - master
jobs:
  cd:
    needs: ci
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/download-artifact@master
      with:
        name: public
    - uses: opspresso/action-s3-sync@master
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: "us-east-1"
        FROM_PATH: "./public/"
        DEST_PATH: "s3://www.robertclarke.com/"